name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  UV_HTTP_TIMEOUT: 300  # Increase timeout for large packages

permissions:
  contents: write

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/ssbc
    permissions:
      contents: write  # Required for creating releases
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          uv sync --extra test

      - name: Run tests
        run: |
          uv run --extra test pytest

      - name: Build package
        run: |
          uv build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
          draft: false
          prerelease: false
